
services: 
  php_8.3.6:
    build:
      context: .
      dockerfile: Dockerfile
    # ports:
    #   - 8000:8000
    #   - 5173:5173
    volumes:
      - ../..:/workspaces:cached
      - "~/.ssh:/home/dss/.ssh"
      - "~/.gitconfig:/home/dss/.gitconfig"
    hostname: dss
    user: dss
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
    
    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally. 
    # (Adding the "ports" property to this file will not forward from a Codespace.)


  db:
    image: mysql:8.0
    # ports:
    #   - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: dss
      MYSQL_DATABASE: dss
      MYSQL_USER: dss
      MYSQL_PASSWORD: dss
      
    command: --default-authentication-plugin=mysql_native_password
    
    
  adminer:
    image: adminer
    # ports:
    #   - 8080:8080
    

volumes:
  mysql-data:
